<!DOCTYPE html>
<html>
<head>
    <title>Miniframework WP Test</title>
    <!-- CSS should be enqueued by WordPress via admin_enqueue_scripts -->
</head>
<body>
    <h1>Miniframework WordPress Integration Test</h1>
    
    <div class="test-wp-message">
        <p>Data from WordPress: <?php echo htmlspecialchars(isset($this->wp_data) ? $this->wp_data : 'No data'); ?></p>
    </div>

    <p>Current Miniframework Plugin URL (generated by mf_plugin_url): 
        <a href="<?php echo htmlspecialchars(isset($this->plugin_page_url) ? $this->plugin_page_url : '#'); ?>">
            <?php echo htmlspecialchars(isset($this->plugin_page_url) ? $this->plugin_page_url : '#'); ?>
        </a>
    </p>

    <button id="test-js-button">Test JS Button</button>

    <p>If `default.css` is loaded, the box above might have a border or special styling.</p>
    <p>If `demo.js` is loaded and working with jQuery, clicking the button might do something (e.g., alert).</p>
    
    <script type="text/javascript">
        // Simple test for demo.js (if it uses jQuery and has a function like miniframework_test_button_click)
        // This is just to help verify, the actual demo.js functionality is unknown.
        if (typeof jQuery !== 'undefined') {
            jQuery(document).ready(function($) {
                $('#test-js-button').on('click', function() {
                    if (typeof miniframework_test_button_click === 'function') {
                        miniframework_test_button_click();
                    } else {
                        alert('jQuery is loaded, but miniframework_test_button_click function not found in demo.js.');
                    }
                });
            });
        } else {
            console.error("jQuery not loaded, cannot test demo.js interaction.");
        }
    </script>
    <!-- JS should be enqueued by WordPress via admin_enqueue_scripts -->
</body>
</html>
